# Generated by Django 4.1 on 2023-12-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0002_remove_shoppinglist_user_shoppinglist_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='user_id',
        ),
    ]
