# Generated by Django 5.0 on 2023-12-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0003_shoppinglist_items_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='items',
            field=models.TextField(blank=True),
        ),
    ]
