# Generated by Django 4.1 on 2023-12-21 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0003_remove_shoppinglist_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='items',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
