# Generated by Django 5.0 on 2023-12-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0004_remove_shoppinglist_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='items',
            field=models.JSONField(default=list),
        ),
    ]
