# Generated by Django 4.1 on 2023-12-22 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0004_shoppinglist_user_alter_shoppinglist_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
